platform :ios, '15.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

flutter_application_path = '../..'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'example_ios' do
  use_frameworks!
  use_modular_headers!

  install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
  flutter_post_install(installer)
end
